#!/bin/bash
#SBATCH --job-name=Bi                      # Job name
#SBATCH --output=output.out                # Standard output log
#SBATCH --error=error.error                # Standard error log
#SBATCH --time=4-00:00:00                  # Time limit (4 days)
#SBATCH --mem=0                            # Memory limit (0 means no limit)
#SBATCH --ntasks=64                        # Total number of tasks (adjust based on your application)
#SBATCH --partition=bansil2                # Partition name
#SBATCH -N 1                               # Number of nodes (set to 1 for a single node)

# Load necessary modules
module load intel/compilers-2022.0.1
module load intel/mpi-2021.5.0
module load hdf5/1.12.1-intel2022

# Source environment setup
source /shared/centos7/intel/oneapi/2021.3.0/setvars.sh
source /home/t.hsu/miniconda3/bin/activate
conda activate minideeph

# Print a message indicating the job is starting
echo "Job starting at: $(date)"

# Execute the deeph-train command
deeph-inference --config inference.ini

# Print a message indicating the job is done
echo "Job completed at: $(date)"

