#!/bin/bash
#SBATCH --job-name=Bi
#SBATCH --output=output.out
#SBATCH --error=error.error
#SBATCH --time=4-00:00:00
#SBATCH --mem=0
#SBATCH --ntasks-per-node=64
#SBATCH --partition=bansil2
#SBATCH -N 4
#SBATCH --constraint=ib,zen2

module load intel/compilers-2022.0.1
module load intel/mpi-2021.5.0
module load hdf5/1.12.1-intel2022

source /shared/centos7/intel/oneapi/2021.3.0/setvars.sh


cd "/home/t.hsu/example2/work_dir/olp/5_4"
mkdir output
mpirun -np 64 /home/t.hsu/openmx_overlap/source/openmx openmx_in.dat > openmx.std

echo "All tasks completed."

